config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'

  resources :users

  get 'session/new'

  #LOGIN
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

  #PROJECTS
  resources :projects do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action :lucky_number
  before_action :fetch_user
    # Before any request in our system is handled, try and define @current_user (call fetch_user to do that)

  private
    def lucky_number
      @lucky_number = Random.rand(1..100)
    end

    def fetch_user
      @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
      session[:user_id] = nil unless @current_user.present?

      # Check in the session variable
        # If there is a key called :user_id
          # Create an instance variable called @current_user that can be used on every page
          # If you can't find a user with that ID
            # Set session[:user_id] to nil
        # If there isn't a key called user_id
          # Do nothing
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.new(comment_params)
    @comment.name = @current_user.name
    @comment.user = @current_user
    @comment.save

    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @comment = @project.comments.find(params[:id])
    @comment.destroy
    redirect_to project_path(@project)
  end

  private
    def comment_params
      params.require(:comment).permit(:name, :post)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @all_projects = Project.all
    # @project = Project.find_by(id: params["id"])
  end

  def show
    @project = Project.find_by(id: params["id"])
    @comments = Comment.where( project_id: @project.id )
  end

  def new
    @project = Project.new
  end

  def create
    project = Project.new( project_params() )
    cloudinary = Cloudinary::Uploader.upload( params[ "project" ][ "link" ] )
    project.image = cloudinary["url"]
    project.user = @current_user
    project.save

    redirect_to "/projects/#{project.id}"
  end

  def edit
    @project = Project.find_by(id: params["id"])
  end

  def update
    project = Project.find_by(id: params["id"])
    project.update( project_params() )
    redirect_to project_path(project)
  end

  def destroy
    project = Project.find_by(id: params["id"])
    project.destroy
    redirect_to projects_path()
  end

  private
    def project_params
      params.require(:project).permit(:title, :date, :image, :user_id)
    end

    def authorise
      unless @current_user
      flash[:error] = "You need to be logged in for that"
      redirect_to "/login"
    end
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  email = params["email"]
  password = params["password"]

  user = User.find_by(email: email)
  # If the user exists and you provided the right password
  if user.present? && user.authenticate(password)

    session[:user_id] = user.id
    redirect_to "/users"

  else
    flash[:login_error] = "The password or email was incorrect"
    # Show the login form again (potentially with a temporary message)
    render :new # Show the new form
  end
end

  def destroy
    session[:user_id] = nil
    redirect_to "/users"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_if_logged_out, only: [:new, :create]
  before_action :check_if_logged_in, only: [:edit, :update]

  def index
    @all_users = User.all
    # @user = User.find_by(id: params['id'])
  end

  def show
    @user = User.find_by(id: params['id'])
    # raise "hell"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path( @user )
    else
      render :new # Show them the Sign Up form again
    end
  end

  def edit
    @user = User.find_by(id: params["id"])
  end

  def update
    project = Project.find_by(id: params["id"])
    project.update( project_strong_params() )
    redirect_to "/projects/#{project.id}"
  end

  def destroy
    projecy = Project.find_by(id: params["id"])
    project.destroy
    redirect_to "/projects"
  end

   private
       def project_strong_params
         params.require(:project).permit(:title, :date, :image)
       end

      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

      def check_if_logged_out
        if @current_user
          flash[:error] = "You are already logged in"
          redirect_to "/users"
        end
      end

      def check_if_logged_in
        unless @current_user
          flash[:error] = "You need to be logged in for that"
          redirect_to "/login"
        end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.post %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.project, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@project, @project.comments.build]) do |f| %>
  <!-- <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p> -->
  <p>
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </p>
  <p>
      <button class="btn waves-effect waves-light #f06292 pink lighten-2" type="submit" name="action">Submit</button>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DribbleApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>

    <nav>
      <div class="nav-wrapper" >
        <a href="/users" class="brand-logo">Dribble</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down" >
          <% if @current_user %>
              <li><a href="/users">All designers</a></li>
              <li><a href="/projects">All projects</a></li>
              <li><a href="/projects/new">New project</a></li>
              <li><%= link_to "Log Out", "/logout", method: :delete %></li>
              <li><a href= "user_path(@current_user)">Hi <%= @current_user.name %></a></li>

          <% else %>
              <li><a href="/login">Sign In</a></li>
              <li><a href="/users/new">Sign Up</a></li>
          <% end %>
        </ul>
      </div>
    </nav>

  </header>

  <main>
    <%= yield %>
  </main>


  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Show and tell for designers</h5>
          <p class="grey-text text-lighten-4">
                What are you working on? Dribbble is a community of designers sharing screenshots of their work, process, and projects.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Contact</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
       © 2017 Dribble. All screenshots © their respective owners.
      </div>
    </div>
  </footer>


</body>
</html>

app/views/projects/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 #ffffff white">

        <%= form_for(@project, :html => { :multipart => true }) do |f| %>
          <p>
            <%= f.label :title %>
            <%= f.text_field :title, required: true %>
          </p>
          <p>
            <%= f.label :date %>
            <%= f.date_field :date, required: true %>
          </p>
          <p>
            <%= f.label :description %>
            <%= f.text_field :description %>
          </p>
          <p>
            <%= f.label :link %>
            <%= f.file_field :link%>
          </p>

            <button class="btn waves-effect waves-light #f06292 pink lighten-2" type="submit" name="action">Submit</button>
        <% end %>

      </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render( partial: "form" ) %>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<% @all_projects.each do |project| %>

<div class="row">
    <div class="col s12 m6 xl4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="<%= project.image %>" >
        </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"> <%= project.title %> </span>
            <p>Project: <%= link_to(project.title, "/projects/#{project.id}", class: "a-links")%></p>
            <p>Designer: <a class = "a-links" href="/users/<%= project.user.id %>"> <%= project.user.name %></a></a></p>
          </div>

        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= project.title %><i class="material-icons right">close</i></span>
          <p><%= project.description %></p>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/projects/new.html.erb
<h1>Create a Project</h1>

<%= render( partial: "form" ) %>

app/views/projects/show.html.erb
<h1>  </h1>


  <div class="container">
    <div class="row">
      <div class="col s12 #ffffff white">
        <div class="center">
          <h1><%= @project.title %></h1>
              <p>
                by <%= link_to(@project.user.name, "/users/#{@project.user_id}") %>
                on <%= @project.date.strftime("%B %d, %Y") %>
              </p>

              <div class = img>
              <% if @project.image %>
                <%= image_tag(@project.image) %>
              <% end %>
              </div>

              <p>
                <%= @project.description %>
              </p>
        </div>


            <h2>Comments</h2>

            <hr>

            <%= render @project.comments %>

            <hr>

            <h2>Add a comment:</h2>

            <%= render 'comments/form' %>

            <p>
              More from <%= link_to(@project.user.name, "/users/#{@project.user_id}") %>
            </p>
          </div>


              <hr>
              <div class="controls">
                <% if @current_user && @current_user.id == @project.user_id  %>
                  <%= link_to("Edit this project", edit_project_path(@project)) %>
                  <%= link_to("Delete this project", project_path(@project), method: :delete, data: { confirm: "Are you sure?" }) %>
                <% end %>
              </div>
                <%= link_to 'Back', projects_path %>
        </div>
    </div>
</div>

app/views/session/new.html.erb
<h1>Login</h1>

<div class="container">
  <div class="row">
    <div class="col s12 #ffffff white">
      <% if flash[:login_error] %>
        <p>
          <%= flash[:login_error] %>
        </p>
      <% end %>

      <%= form_tag "/login" do %>
        <p>
          <%= label_tag :email %>
          <%= email_field_tag :email %>
        </p>
        <p>
          <%= label_tag :password %>
          <%= password_field_tag :password %>
        </p>

        <button class="btn waves-effect waves-light #f06292 pink lighten-2" type="submit" name="action">Submit</button>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 #ffffff white">
      <% unless @user.errors.full_messages.empty? %>

        <% @user.errors.full_messages.each do |msg| %>
          <p>
            <%= msg %>
          </p>
        <% end %>

      <% end %>

      <p>Dribble is a show and tell community for designers
      Sign up to find, follow and hire members of our small but vibrant community of designers, icon artists, illustrators, interface designers, typographers, and other creative folks.</p>

      <%= form_for @user do |f| %>
        <p>
          <%= f.label :name %>
          <%= f.text_field :name, required: true %>
        </p>
        <p>
          <%= f.label :email %>
          <%= f.email_field :email, required: true %>
        </p>
        <p>
          <%= f.label :location %>
          <%= f.text_field :location, required: true %>
        </p>
        <p>
          <%= f.label :image %>
          <%= f.url_field :image, required: false %>
        </p>
        <p>
          <%= f.label :skills %>
          <%= f.text_field :skills, required: false %>
        </p>
        <p>
          <%= f.label :password %>
          <%= f.password_field :password, required: true %>
        </p>
        <p>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, required: true %>
        </p>

          <button class="btn waves-effect waves-light #f06292 pink lighten-2" type="submit" name="action">Submit</button>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit Designer</h1>

<%= form_for @user, url: "/users/#{@user.id}" do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :skills %>
    <%= f.text_field :skills %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.url_field :image %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.date_field :email %>
  </p>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>All Designers</h1>

<% @all_users.each do |user| %>

<div class="row">
    <div class="col s12 m6 xl4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
        <img class="activator users-index" src="<%= user.image %>">
        </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"> <%= user.name %> </span>
          </div>
          <p>Designer: <a class = "a-links" <%= link_to(user.name, "/users/#{user.id}") %></a></a></p>

        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= user.name %><i class="material-icons right">close</i></span>
          <ul>
            <li>Name: <%= user.name %></li>
            <li>Email: <%= user.email %></li>
            <li>Location: <%= user.location %></li>
            <li>Skills: <%= user.skills %></li>
          </ul>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: "form" %>

app/views/users/show.html.erb
<h1>      </h1>

<div class="container">
  <div class="row">
    <div class="col s12 #ffffff white">
      <div class="center">

        <h1><%= @user.name %></h1>

          <div class = img>
          <%= image_tag( @user.image ) %>
          </div>

          <ul>
            <li>Name: <%= @user.name %></li>
            <li>Location: <%= @user.location %></li>
            <li>Skills: <%= @user.skills %></li>
            <li>Hire Me: <%= @user.email %></li>
          </ul>

          <h3>More projects from <%= @user.name %></h3>

          <div class="project-links">
            <% @user.projects.each do |project| %>
              <p>
                <%= link_to(project.title, project_path(project)) %>
              </p>
            <% end %>
          </div>

          <div class="controls">
            <% if @current_user && @current_user.id == @user.id  %>
              <%= link_to("Edit Profile", "/users/#{@user.id}/edit") %>

              <%= link_to("Delete Profile", "/users/#{@user.id}", method: :delete, data: { confirm: "Are you sure?" }) %>
            <% end %>
          </div>

        </div>
      </div>
  </div>
</div>